python main.py \
    --task=triplet \
    --mode=train \
    --dataset=shulex \
    --max_sequence_len=128 \
    --batch_size=32 \
    --use_fgm=True \
    --use_fp16=True \
    --epochs=10 \
    --early_stop=20 \
    --lr=5e-5 \
    --label_smoothing=0.05 \
    --do_lower_case=True \
    --bert_model_path=/root/autodl-nas/pretrain-models/reviews-roberta \
    --bert_tokenizer_path=/root/autodl-nas/pretrain-models/roberta-base
